
[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/dghubble/sling"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kristjank/goark-node"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.2"

[[constraint]]
  name = "github.com/masato25/ark-go"
  branch = "dev"
